# fly.toml file generated for hyperlocal on 2023-04-14T13:15:54+05:30

app = "hyperlocal"
kill_timeout = 0
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  cmd = "npm run build"