# fly.toml app configuration file generated for hyperlocal on 2023-05-21T14:16:36+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hyperlocal"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
